#' Configure movement random effects 
#' 
#' The generate_move() function is used to configure movement random effects
#' 
#' @param basic_info Information generated by \code{\link{generate_basic_info}}.
#' Note: NAA_where has to be specified in basic_info using \code{\link{generate_NAA_where}}.
#' @param move.type Movement type
#'   \itemize{
#'     \item \code{1} unidirectional movement
#'     \item \code{2} bidirectional movement (default)
#'     \item \code{3} no movement
#'     }
#' @param move.rate Movement rate  (default = 0.3)
#' @param move.re Movement random effects
#'   \itemize{
#'     \item \code{"constant"} constant movement rate across years and ages (default).
#'     \item \code{"iid_y"} movement rate deviations vary by year, but uncorrelated.
#'     \item \code{"iid_a"} movement rate deviations vary by age, but uncorrelated.
#'     \item \code{"ar1_y"} movement rate deviations correlated by year (AR1).
#'     \item \code{"ar1_a"} movement rate deviations correlated by age (AR1).
#'     }
#'     
#' @return a named list with the following components:
#'   \describe{
#'     \item{$stock_move}{length = n_stocks, T/F whether each stock can move. If not provided then movement will be defined below for all stocks.}
#'     \item{$separable}{length = n_stocks, T/F whether movement should be modeled separably from mortality or both occuring simultaneously.}
#'     \item{$must_move}{array (n_stocks x n_seasons x n_regions) 0/1 indicator whether movement from region must occur.}
#'     \item{$can_move}{array (n_stocks x n_seasons x n_regions x n_regions) 0/1 indicator whether movement can occur from one region to another.}
#'   }
#'   
#' @export
#'
#' @seealso \code{\link{set_move}} and \code{\link{generate_NAA_where}}
#' 
#' @examples
#' \dontrun{
#' data <- generate_basic_info()
#' data <- generate_move(data, move.type = 2, move.rate = 0.3, move.re = "constant")
#' }
#' 
generate_move <- function(basic_info = basic_info, 
                          move.type = 2,
                          move.rate = 0.3, 
                          move.re = "constant") {
  if(any(names(basic_info) %in% "mig_type")) sep_move = !as.logical(basic_info$mig_type)
  n_stocks = basic_info$n_stocks
  n_regions = basic_info$n_regions
  if (n_stocks != n_regions) stop("The current version only allows n_stocks = n_regions") 
  n_seasons = basic_info$n_seasons
  fracyr_spawn = basic_info$fracyr_spawn
  spawntime = assign_season(fracyr_spawn,n_seasons)
  if (length(spawntime) > 1) cat("Spawntime is a vector and first element is used \n")
  spawntime = spawntime[1] 
  tmp = 1:n_seasons
  movetime = tmp[tmp != spawntime]
  
  if (move.type != 3 & is.null(move.re)) cat("\nmove.re must be specified unless move.type = 3!")
  if (move.type != 3 & is.null(move.rate)) cat("\nmove.rate must be specified unless move.type = 3!")
  
  if (move.type == 1) {
    move_mu = move.rate
    tmp = c(TRUE,rep(FALSE,n_stocks-1)) # assume only stock 1 can move
    cat(paste0("Only stock 1 'can' move (default) \nMovement rate is ",move.rate)) 
    move = list(stock_move = tmp, separable = sep_move) # stock1 moves, stock2 doesn't
    move$must_move = array(0,dim = c(n_stocks,n_seasons,n_regions))
    move$can_move = array(0, dim = c(n_stocks,n_seasons,n_regions,n_regions))
    move$must_move[1,spawntime,which(1:n_regions != 1)] <- 1 # 1st element means stock # and 3rd element means region #
    move$can_move[1,movetime,,] <- 1 #only north stock can move and in seasons prior to spawning and after spawning
    move$can_move[1,spawntime,which(1:n_regions != 1),] <- 1 #north stock can (and must) move in last season prior to spawning back to north 
    move$mean_vals <- array(move_mu, dim = c(n_stocks,n_seasons,n_regions,n_regions-1))
    
    if (move.re == "ar1_y"){
      cat("\nMovement is treated to be autocorrelated by years") 
      move$use_prior <- array(0, dim = c(n_stocks,n_seasons,n_regions,n_regions-1))
      move$use_prior[1:n_stocks,1,1:n_stocks,1] <- 1
      move$prior_sigma <- array(0.2, dim = c(n_stocks,n_seasons,n_regions,n_regions-1))
      move$year_re = matrix("none", n_regions, n_regions -1)
      move$year_re[1,] <- "ar1" # only for stock 1
      move$mean_model = matrix("constant", n_regions,n_regions -1)
    }
    
    if (move.re == "ar1_a"){
      cat("\nMovement is treated to be autocorrelated by ages") 
      move$use_prior <- array(0, dim = c(n_stocks,n_seasons,n_regions,n_regions-1))
      move$use_prior[1:n_stocks,1,1:n_stocks,1] <- 1
      move$prior_sigma <- array(0.2, dim = c(n_stocks,n_seasons,n_regions,n_regions-1))
      move$age_re = matrix("none", n_regions, n_regions -1)
      move$age_re[1,] <- "ar1" # only for stock 1
      move$mean_model = matrix("constant", n_regions,n_regions -1)
    }
    
    if (move.re == "iid_y"){
      cat("\nMovement is treated to be autocorrelated by years") 
      move$use_prior <- array(0, dim = c(n_stocks,n_seasons,n_regions,n_regions-1))
      move$use_prior[1:n_stocks,1,1:n_stocks,1] <- 1
      move$prior_sigma <- array(0.2, dim = c(n_stocks,n_seasons,n_regions,n_regions-1))
      move$year_re = matrix("none", n_regions, n_regions -1)
      move$year_re[1,] <- "iid" # only for stock 1
      move$mean_model = matrix("constant", n_regions,n_regions -1)
    }
    
    if (move.re == "iid_a"){
      cat("\nMovement is treated to be autocorrelated by years") 
      move$use_prior <- array(0, dim = c(n_stocks,n_seasons,n_regions,n_regions-1))
      move$use_prior[1:n_stocks,1,1:n_stocks,1] <- 1
      move$prior_sigma <- array(0.2, dim = c(n_stocks,n_seasons,n_regions,n_regions-1))
      move$age_re = matrix("none", n_regions, n_regions -1)
      move$age_re[1,] <- "iid" # only for stock 1
      move$mean_model = matrix("constant", n_regions,n_regions -1)
    }
    
    if (move.re == "constant") cat("\nMovement is assumed at a constant rate without random effects") 
  } 
  
  if (move.type == 2) {
    move_mu = rep(0.1,n_stocks)
    move_mu[1] = move.rate
    tmp = c(rep(TRUE,n_stocks)) 
    cat(paste0("All stocks 'can' move (default) \n"))
    cat(paste0("Movement rate for stock 1 is ",move.rate,"\nMovement rate for the other stocks is 0.1")) 
    move = list(stock_move = tmp, separable = sep_move) # stock 1 and 2 both move
    move$must_move = array(0,dim = c(n_stocks,n_seasons,n_regions))
    move$can_move = array(0, dim = c(n_stocks,n_seasons,n_regions,n_regions))
    
    for (s in 1:n_stocks) {
      move$must_move[s,spawntime,which(1:n_regions != s)] <- 1
      move$can_move[s,movetime,,] <- 1
      move$can_move[s,spawntime,which(1:n_regions != s),] <- 1
    }
    
    move$mean_vals <- array(0, dim = c(n_stocks,n_seasons,n_regions,n_regions-1))
    
    for (r in 1:n_regions){
      move$mean_vals[,,r,] <- move_mu[r]
    }
    
    if (move.re == "ar1_y"){
      cat("\nMovement is treated to be autocorrelated by years") 
      move$use_prior <- array(0, dim = c(n_stocks,n_seasons,n_regions,n_regions-1))
      move$use_prior[1:n_stocks,1,1:n_stocks,1] <- 1
      move$prior_sigma <- array(0.2, dim = c(n_stocks,n_seasons,n_regions,n_regions-1))
      move$year_re = matrix("ar1", n_regions, n_regions -1)
      move$year_re[] <- "ar1"
      move$mean_model = matrix("constant", n_regions,n_regions -1)
    }
    
    if (move.re == "ar1_a"){
      ("\nMovement is treated to be autocorrelated by ages") 
      move$use_prior <- array(0, dim = c(n_stocks,n_seasons,n_regions,n_regions-1))
      move$use_prior[1:n_stocks,1,1:n_stocks,1] <- 1
      move$prior_sigma <- array(0.2, dim = c(n_stocks,n_seasons,n_regions,n_regions-1))
      move$age_re = matrix("ar1", n_regions, n_regions -1)
      move$age_re[] <- "ar1"
      move$mean_model = matrix("constant", n_regions,n_regions -1)
    }
    
    if (move.re == "iid_y"){
      cat("\nMovement is treated to be varying by years") 
      move$use_prior <- array(0, dim = c(n_stocks,n_seasons,n_regions,n_regions-1))
      move$use_prior[1:n_stocks,1,1:n_stocks,1] <- 1
      move$prior_sigma <- array(0.2, dim = c(n_stocks,n_seasons,n_regions,n_regions-1))
      move$year_re = matrix("none", n_regions, n_regions -1)
      move$year_re[] <- "iid"
      move$mean_model = matrix("constant", n_regions,n_regions -1)
      
      #sigma_vals = 0.2
      #move$mu_repars = array(0, dim = c(n_stocks, n_seasons, n_regions, n_regions-1, 3))
      #move$mu_repars[,,,,1] = log(sigma_vals)
    }
    
    if (move.re == "iid_a"){
      cat("\nMovement is treated to be varying by years") 
      move$use_prior <- array(0, dim = c(n_stocks,n_seasons,n_regions,n_regions-1))
      move$use_prior[1:n_stocks,1,1:n_stocks,1] <- 1
      move$prior_sigma <- array(0.2, dim = c(n_stocks,n_seasons,n_regions,n_regions-1))
      move$age_re = matrix("none", n_regions, n_regions -1)
      move$age_re[] <- "iid"
      move$mean_model = matrix("constant", n_regions,n_regions -1)
    }
    
    if (move.re == "constant") cat("\nMovement is assumed at a constant rate without random effects") 
  }
  
  if (move.type == 3) {
    move = NULL
  }
  
  if (n_stocks == 1 & n_regions == 1) move = NULL
  
  return(move)
}

assign_season <- function(fraction,n_seasons) {
  season_fraction <- 1/n_seasons
  season <- ceiling(fraction/season_fraction)
  return(season)
}
#inv_trans_rho <- function(rho, s = 1) (log(rho+1) - log(1-rho))/s

#if(!is.null(move$sigma_vals)){
#  par$mu_repars[,,,1] = log(move$sigma_vals)
#}
#if(!is.null(move$cor_vals)){
#  par$mu_repars[,,,,2] = inv_trans_rho(move$cor_vals[,,,,1])
#  par$mu_repars[,,,,3] = inv_trans_rho(move$cor_vals[,,,,2])
#}


#par$mu_repars[,,,1] is sigma for movement
#par$mu_repars[,,,,2] = inv_trans_rho(move$cor_vals[,,,,1]) rho for age
#par$mu_repars[,,,,3] = inv_trans_rho(move$cor_vals[,,,,2]) rho for year
